# .gemini/commands/workflow/next.toml
description = "Завершает текущий этап: обновляет PLAN.md, делает коммит и переходит к следующему пункту."

prompt = """
Эта команда запускает автоматический протокол: ты в `PLAN.md` пункт над которым мы работали, отмечаешь его как выполненный, делаешь коммит в Git и готовишься к следующему шагу. Это наша точка синхронизации.
"""